config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  get 'authentication/sign_up'
  get 'authentication/sign_in'
  root 'pages#home'
  get 'announcement/:id', to: 'pages#announcement', as: :announcement
  get 'product/:id', to: 'pages#product', as: :product
  get 'order_history', to: 'pages#order_history', as: :order_history
  get 'order_product', to: 'pages#order_product'
  get 'contact_us', to: 'pages#contact_us'
  get 'add_to_cart', to: 'pages#add_to_cart'
  get 'get_product', to: 'pages#get_product'
  get 'contact', to: 'pages#contact', as: :contact
  get 'blogs', to: 'pages#blogs', as: :blogs
  get 'blog/:id', to: 'pages#blog', as: :blog
  get 'get_local_storage', to: 'pages#get_local_storage'
  get 'checkout_steps/get_local_storage', to: 'checkout_steps#get_local_storage'
  get 'cart',  to: 'pages#cart'
  get 'reply', to: 'pages#reply'
  get 'increase_product_quantity', to: 'pages#increase_product_quantity'
  get 'decrease_product_quantity', to: 'pages#decrease_product_quantity'
  get 'delete_cart_product', to: 'pages#delete_cart_product'
  get 'get_sub_total', to: 'pages#get_sub_total'
  get '/execute', to: 'checkout_steps#execute'
  get '/redirect_to_paypal', to: 'checkout_steps#redirect_to_paypal', as: :paypal
  get 'continue_to_shipping_method', to: 'checkout_steps#continue_to_shipping_method'
  get 'complete_order', to: 'checkout_steps#complete_order'
  get 'get_nearest_city', to: 'checkout_steps#get_nearest_city'
  get 'admin/login', to: 'admin_authentication#admin_login_page'
  get 'admin_login_action', to: 'admin_authentication#admin_login_action'
  resources :checkout_steps, as: :checkout_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/announcement.rb
# frozen_string_literal: true

class Announcement < ApplicationRecord
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  mount_uploader :image, ImageUploader
  has_many :reply_blogs
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :customer
  has_many :cart_products
end

app/models/cart_product.rb
# frozen_string_literal: true

class CartProduct < ApplicationRecord
  require 'paypal-sdk-rest'
  include RailsAdminCharts
  include PayPal::SDK::REST
  belongs_to :cart, optional: true
  belongs_to :product


  # def self.chart_type
  #   'bar'
  # end

  PayPal::SDK::REST.set_config(
    mode: 'sandbox', # "sandbox" or "live"
    client_id: 'AYjZT2tas5_xjKODvKSW1DEXVieC0wn4EWR4H_bn7vfP4PwdjTlY5kjL640PZgRhrWbk71Fy62tO87IJ',
    client_secret: 'EDuYKlUbkwgH8wGLetN0Gk6a0l4BUBuCFqh0JIvuXavIKBrewa5G5AAA7vbPpe_xd08GWfzSSvSuO9BX'
  )

  def paypal_url(additional, cart_product, url)
    @url = url
    itemlist = []
    @total = []
    @index = 0
    cart_product.each do |product|
      @id = product.product_id
      @price    = product.product.price
      @quantity = product.quantity
      @index += 1
      Product.where(id: @id).each_with_index do |prod, _index|
        itemlist << {
          name: prod.name.to_s,
          price: @price.to_s,
          currency: 'PHP',
          quantity: @quantity.to_s
        }
      end
      itemlist << {
        name: 'Shipping Fee',
        price: additional,
        currency: 'PHP',
        quantity: 1
      }
    end

    itemlist.each do |items|
      pp items
      @total << items[:price].to_i * items[:quantity].to_i
    end
    pp itemlist
    @grand_total = @total.sum
    pp itemlist
    pp @grand_total
    pp @total.sum.to_s
    @payment = Payment.new(
      intent: 'sale',
      payer: {
        payment_method: 'paypal'
      },
      redirect_urls: {
        return_url: "#{@url}/execute",
        cancel_url: "#{@url}/cart"
      },
      transactions: [{
        item_list: {
          items: itemlist
        },
        amount: {
          total: @grand_total.to_s,
          currency: 'PHP'
        },
        description: 'This is the payment transaction description.'
      }]
    )
    if @payment.create
      @redirect_url = @payment.links.find { |v| v.rel == 'approval_url' }.href
    else
      logger.error @payment.error.inspect
    end
  end
end

# # Credentials for Classic APIs
# app_id: APP-80W284485P519543T
# username: marvn.jimena-facilitator_api1.gmail.com
# password: QLV3K2XZLGWQP2H3
# signature: A9A0gZTWcGyirG.qnLuzNtP0Yj-IA5IeOJyTR7Ni6K.l.dBQqkq9Armq
# # # With Certificate
# # cert_path: "config/cert_key.pem"
# sandbox_email_address: Platform.sdk.seller@gmail.com

# # IP Address
# ip_address: 127.0.0.1
# # HTTP Proxy
# http_proxy: http://proxy-ipaddress:3129/

app/models/charging_capacity.rb
# frozen_string_literal: true

class ChargingCapacity < ApplicationRecord
  belongs_to :product, optional: true
  mount_uploader :image, ImageUploader
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
end

app/models/contact_u.rb
# frozen_string_literal: true

class ContactU < ApplicationRecord
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_secure_password
  has_many :orders
  has_one :cart
  has_many :customer_shipping_address
end

app/models/faq.rb
# frozen_string_literal: true

class Faq < ApplicationRecord
  belongs_to :product
end

app/models/feature_image.rb
# frozen_string_literal: true

class FeatureImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :product, optional: true
end

app/models/feature_info.rb
	# frozen_string_literal: true

class FeatureInfo < ApplicationRecord
  belongs_to :product
  # mount_uploader :image, ImageUploader
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer, optional: true
  belongs_to :order_status, optional: true
  belongs_to :payment_order_status, optional: true
  belongs_to :customer_shipping_address, optional: true
  has_many :order_products
end

app/models/order_product.rb
# frozen_string_literal: true

class OrderProduct < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :product, optional: true
end

app/models/order_status.rb
# frozen_string_literal: true

class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :cart_products
  mount_uploader :image, ImageUploader
  has_many :faqs
  has_many :technical_specifications
  has_one :technical_specification_image
  has_many :charging_capacity
  has_many :feature_images
  has_many :order_products
  # has_one :feature_produc
  # has_one :product_feature
  has_many :feature_infos
  # has_one :product
end

app/models/product_feature.rb
# frozen_string_literal: true

class ProductFeature < ApplicationRecord
  mount_uploader :image, ImageUploader
  # belongs_to :product
end

app/models/reply_blog.rb
# frozen_string_literal: true

class ReplyBlog < ApplicationRecord
  belongs_to :blog, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # :rememberable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
end

app/models/wall_of_power.rb
class WallOfPower < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/views/pages/blogs.html.erb
<div class="container">
	<!-- Section: Blog v.3 -->
	<section class="my-5">
    
	  <!-- Section heading -->
	  <h2 class="h1-responsive font-weight-bold text-center my-5">Blog</h2>
		<% @blogs.each do |blog| %> 
		  <!-- Grid row -->
			  <div class="row">

			    <!-- Grid column -->
			    <div class="col-lg-5 col-xl-4">

			      <!-- Featured image -->
			      <div class="view overlay rounded z-depth-1-half mb-lg-0 mb-4">
			        <%= image_tag blog.image_url, class: 'img img-thumbnail', style: 'width:100%;height:350px' %>
			        <a>
			          <div class="mask rgba-white-slight"></div>
			        </a>
			      </div>

			    </div>
			    <!-- Grid column -->

			    <!-- Grid column -->
			    <div class="col-lg-7 col-xl-8">

			      <!-- Post title -->
			      <h3 class="font-weight-bold mb-3"><strong><%= "#{blog.name} - #{blog.title}" %></strong></h3>
			      <!-- Excerpt -->
			    <!--   <p class="dark-grey-text">Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit
			        quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus
			        et aut officiis debitis cum soluta nobis est eligendi placeat facere aut rerum.</p> -->
			      <!-- Post data -->
			      <p><%= blog.created_at.strftime("%m/%d/%Y") %></p>
                  <%= link_to 'View', blog_path(blog.id), class: 'btn btn-primary btn-md' %>
			    </div>
			    <!-- Grid column -->

			  </div>
		  <!-- Grid row -->

		  <hr class="my-5">
        <% end %> 

	  <!-- Grid row -->
	
	    <!-- Grid column -->

	  </div>
	  <!-- Grid row -->

	</section>
<!-- Section: Blog v.3 -->
</div>

app/views/pages/contact.html.erb
<%= render 'shared/contact' %>

app/views/pages/home.html.erb
<%= render 'shared/carousel' %>
<div class="container">
  <!-- Section: Products v.2 -->
  <section class="text-center my-5">

  <!-- Grid row -->
  <div class="row">
    <% products.each do |product| %>
     <div class="col-lg-4 col-md-12 mb-lg-0 mb-4">
      <!-- Card -->
      <div class="card card-cascade wider card-ecommerce">
        <!-- Card image -->
        <div class="view view-cascade overlay">
           <%= image_tag product.image_url , class: 'card-img-top' %>  
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>  
        </div>
        <!-- Card content -->
        <div class="card-body card-body-cascade text-center">
          <!-- Category & Title -->
          <a href="" class="text-muted">
            <h5><%= product.name %></h5>
          </a>
          <!-- Description -->
          <p class="card-text"><%= product.product_description %></p>
          <!-- Card footer -->
          <div class="card-footer px-1">
            <span class="float-right">
            	   <%= link_to "Learn More", product_path(product.id.to_i) , class: 'btn text-white btn-learn-more' %>
            </span>
          </div>
        </div>
        <!-- Card content -->
      </div>
      <!-- Card -->
     </div>
    <% end %>
  </div>
  </section>
  <hr>
  <section class="text-center my-5">
  <h3 class="h3-responsive font-weight-bold text-center my-5">PowerLife Products are Built for the Active and Mobile Filipino Lifestyle</h3>
  <p class="grey-text text-center w-responsive mx-auto mb-5">Advance back-up charging solutions ideal for living and traveling in over 7,600 islands</p>

  <!-- Grid row -->
  <div class="row">

    <!-- Grid column -->
    <div class="col-lg-6 col-md-6 mb-lg-0 mb-4">
      <!-- Collection card -->
      <div class="card collection-card z-depth-1-half">
        <!-- Card image -->
        <div class="view zoom">
          <%= image_tag 'brownouts.jpg', class: 'img-fluid'  %>  
          <div class="stripe dark">
            <a>
              <p>Brownouts/Blackouts
                <i class="fas fa-angle-right"></i>
              </p>
            </a>
          </div>
        </div>
        <!-- Card image -->
      </div>
      <!-- Collection card -->
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-6 col-md-6 mb-lg-0 mb-4">
      <!-- Collection card -->
      <div class="card collection-card z-depth-1-half">
        <!-- Card image -->
        <div class="view zoom">
          <%= image_tag 'disasters.jpg', class: 'img-fluid'  %>  
          <div class="stripe dark">
            <a>
              <p>Emergency/Disasters
                <i class="fas fa-angle-right"></i>
              </p>
            </a>
          </div>
        </div>
        <!-- Card image -->
      </div>
      <!-- Collection card -->
    </div>
    <!-- Grid column -->

    <!-- Grid column -->
    <div class="col-lg-6 col-md-6 mb-md-0 mb-4">
      <!-- Collection card -->
      <div class="card collection-card z-depth-1-half">
        <!-- Card image -->
        <div class="view zoom">
          <%= image_tag 'camping.jpg', class: 'img-fluid'  %>  
          <div class="stripe dark">
            <a>
              <p>Camping/Mountaineering
                <i class="fas fa-angle-right"></i>
              </p>
            </a>
          </div>
        </div>
        <!-- Card image -->
      </div>
      <!-- Collection card -->
    </div>
    <!-- Grid column -->

    <!-- Fourth column -->
    <div class="col-lg-6 col-md-6">
      <!-- Collection card -->
      <div class="card collection-card z-depth-1-half">
        <!-- Card image -->
        <div class="view zoom">
           <%= image_tag 'devices.jpg', class: 'img-fluid'  %>  
          <div class="stripe dark">
            <a>
              <p>Electronic Devices
                <i class="fas fa-angle-right"></i>
              </p>
            </a>
          </div>
        </div>
        <!-- Card image -->
      </div>
      <!-- Collection card -->
    </div>
    <!-- Fourth column -->

  </div>
  <!-- Grid row -->
  </section>
   <hr>
   <h3 class="h3-responsive font-weight-bold text-center my-5">PRODUCT FEATURES</h3>
   <p class="grey-text text-center w-responsive mx-auto mb-5">PowerLife products are built with the newest technology.</p> 
	<section class="text-center my-5">
	  <!-- Grid row -->
	  <div class="row">
	    <% product_features.each do |product_feature| %>
		   <div class="col-lg-2 col-md-6 mb-lg-0 mb-4" data-aos="zoom-in">
		      <!-- Card -->
		      <div class="card align-items-center" style="height:200px;">
		        <!-- Card image -->
		        <div class="view overlay">
		          <br>  
		          <%= image_tag product_feature.image_url, class: 'card-img-top'%>  
		          <a>
		            <div class="mask rgba-white-slight"></div>
		          </a>
		        </div>
		        <!-- Card image -->
		        <!-- Card content -->
		        <div class="card-body text-center" style="position:absolute;top:100px">
		          <!-- Category & Title -->
		          <h5>
		            <strong>
		              <%= link_to product_feature.name, nil, class: 'dark-grey-text'%>
		            </strong>
		          </h5>
		        </div>
		        <!-- Card content -->
		      </div>
		      <!-- Card -->
		   </div>
        <% end %>
	  </div>
	</section>
  <hr>
  <section class="text-center my-5">
   <h3 class="h3-responsive font-weight-bold text-center my-5">PRODUCT COMPARISON</h3>
   <p class="grey-text text-center w-responsive mx-auto mb-5">PowerLife products are in a new category of power generators/banks that is revolutionizing the market.</p>
  </section>    
  <div class="row col-md-12">  
     <table class="table table-hover table-responsive">
      <thead>
        <tr style="background-color:#31383d;color:white">
          <th scope="col" colspan="2"></th>
          <th></th>
          <th scope="col">Gas-Powered Generators</th>
          <th scope="col">UPS</th>
          <th scope="col">Power Banks</th>
          <th scope="col">Powerlife</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td colspan="3">Portable</td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
        <tr>
          <td colspan="3">High Capacity</td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
        <tr>
          <td colspan="3">Environmental Friendly</td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
        <tr>
          <td colspan="3">Solar	Enabled</td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
        <tr>
          <td colspan="3">Quiet</td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
        <tr>
          <td colspan="3">Mobile Design</td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-times text-danger"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
          <td><i class="fas fa-check text-success"></i></td>
        </tr>
      </tbody>
     </table>
  </div>
  <hr>
  <!-- Announcement -->
  <section class="text-center my-5">
   <h3 class="h3-responsive font-weight-bold text-center my-5">ANNOUNCEMENT</h3>
  </section>    
	 <div class="row mx-1 announcement-card">
	  <% announcements.each do |announcement|%> 
	   <div class="col-lg-4 col-md-6 mb-4 announcement">
  		 <div class="card card-cascade wider">

  		          <!-- Card image -->
  		          <div class="view view-cascade gradient-card-header peach-gradient">

  		            <!-- Title -->
  		            <h5 class="card-header-title mb-3" style="height:70px"><%= announcement.title %></h5>
  		            <!-- Text -->
  		            <p class="mb-0"><i class="fas fa-calendar mr-2"></i><%= announcement.date.strftime("%B %d, %Y") %></p>
    
  		          </div>

  		          <!-- Card content -->
  		          <div class="card-body card-body-cascade text-center">

  		            <!-- Text -->
  		            <p class="card-text">
  		              <%= truncate(announcement.content, :length =>100 , :omission => '...') %>	
  		            </p>
  		            <!-- Link -->
  		            <a href="#" class="orange-text d-flex flex-row-reverse p-2">
  		              <%= link_to '<h5 class="waves-effect waves-light text-dark">Read more<i class="fas fa-angle-double-right ml-2"></i></h5>'.html_safe, announcement_path(announcement.id) %>
  		            </a>

  		          </div>
  		          <!-- Card content -->
  		 </div>
	   </div>
	  <% end %>
	 </div> 
   <div class="col-md-12">
      <center>
        <a href="#" id="announcement-load">Load More</a>
      </center>  
   </div>
  <hr>
 <!-- Section: Testimonials v.1 -->
<section class="text-center my-5 p-1">

  <!-- Section heading -->
  <h3 class="h3-responsive font-weight-bold my-5" id="wall_of_power">WALL OF POWER</h3>
  <!-- Section description -->
  <p class="dark-grey-text w-responsive mx-auto mb-5">Lorem ipsum dolor sit amet, consectetur adipisicing elit.
    Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam
    eum porro a pariatur veniam.</p>

  <div class="row">
   <% wall_of_power.each do |wop| %>
    <div class="col-lg-4 col-md-4  col-sm-6 col-xs-12 mb-lg-0 mb-4 wall-of-power">
      <!--Card-->
      <div class="card testimonial-card">
        <!--Background color-->
        <div class="card-up info-color"></div>
        <!--Avatar-->
        <div class="avatar mx-auto white">
           <%= image_tag wop.image.url , class: 'rounded-circle img-fluid'%>
        </div>
        <div class="card-body">
          <!--Name-->
          <h4 class="font-weight-bold mb-4"><%= wop.name %></h4>
          <hr>
          <!--Quotation-->
          <p class="dark-grey-text mt-4">Owner of <%= wop.owner_product %></p>
          <p class="dark-grey-text mt-4"><i class="fas fa-quote-left pr-2"></i>
           <%= wop.title %>
          </p>
        </div>
      </div>
      <!--Card-->
    </div>
  <% end %>  
   <div class="col-md-12">
      <center>
        <br>
        <a href="#" id="wall-of-power-load">Load More</a>
      </center>  
   </div>
</section>     
</div>
<%= stylesheet_link_tag 'store-front/style.css' %>
<%= javascript_include_tag 'store-front/home.js' %>

app/views/shared/_nav.html.erb
<!--    <button class="btn btn-secondary" id="logout">Logout</button> -->
<nav class="navbar navbar-expand-lg navbar-dark">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  <a class="navbar-brand" href="/">
     <%= image_tag 'powerlife-logo-w.png', width:'200' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto" id="nav-menu">
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Products</a>
          <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
            <% get_all_products.each do |product| %>
               <%= link_to product.name, product_path(product.id.to_i) , class: 'dropdown-item' %>
            <% end %>
          </div>
         </li>

         <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
         </li>
         <li class="nav-item">
          <%= link_to 'Blog', blogs_path, class: 'nav-link' %>
         </li>
         <li class="nav-item">
          <a data-scroll href="#wall_of_power" class="nav-link">
            Wall of Power
          </a>
         </li>
      </ul>
      <ul class="navbar-nav ml-auto nav-flex-icons" id="is-login-true">
          <li class="nav-item dropdown" id="profile">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-333" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-default"
              aria-labelledby="navbarDropdownMenuLink-333">
              <%= link_to 'Order History', order_history_path, class: 'dropdown-item' %>
              <%= link_to 'Cart', cart_path, class: 'dropdown-item' %>
              <a class="dropdown-item" href="" id="logout">Logout</a>
            </div>
          </li>
      </ul>

      <span class="navbar-text white-text" id="is-login-false">
       <button class="btn btn-sign-in" data-toggle="modal" data-target="#signInModal">Login</button>
       <button class="btn btn-sign-up" data-toggle="modal" data-target="#signUpModal">Register</button>
        
        <div class="modal fade right" id="signInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog modal-side modal-top-right" role="document">
            <div class="modal-content">
              <div class="modal-header login-header">
                <h4 class="modal-title w-100">Sign in</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body mx-3">
                <div class="md-form mb-5">
                  <i class="fas fa-envelope prefix grey-text"></i>
                  <input type="email" id="email" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="email">Your email</label>
                </div>

                <div class="md-form mb-4">
                  <i class="fas fa-lock prefix grey-text"></i>
                  <input type="password" id="pass" class="form-control validate">
                  <label data-error="wrong" data-success="right" for="pass">Your password</label>
                </div>

              </div>
              <div class="modal-footer d-flex justify-content-center">
                <button class="btn btn-sign-in" id="login">Login</button>
              </div>
            </div>
          </div>
        </div>
 

          <div class="modal fade right" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-full-height modal-right" role="document">
              <div class="modal-content">
                <div class="modal-header register-header">
                  <h4 class="modal-title w-100" id="myModalLabel">Sign Up</h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body mx-3">
                    <div class="md-form mb-5">
                      <i class="fas fa-user prefix grey-text"></i>
                      <input type="text" id="fullname" class="form-control">
                      <label data-error="wrong" data-success="right" for="fullname">Your Fullname</label>
                    </div>
                    <div class="md-form mb-5">
                      <i class="fas fa-envelope prefix grey-text"></i>
                      <input type="email" id="email-address" class="form-control">
                      <label data-error="wrong" data-success="right" for="email-address">Your email</label>
                    </div>

                    <div class="md-form mb-4">
                      <i class="fas fa-lock prefix grey-text"></i>
                      <input type="password" id="password" class="form-control">
                      <label data-error="wrong" data-success="right" for="password">Your password</label>
                      <br>
                    </div>

                    <div class="md-form mb-4">
                      <i class="fas fa-lock prefix grey-text"></i>
                      <input type="password" id="re-pass" class="form-control">
                      <label data-error="" data-success="" for="re-pass">Retype Password</label>
                    </div>

                </div>
                <div class="modal-footer justify-content-center">
                  <button type="button" class="btn btn-close" data-dismiss="modal">Close</button>
                  <button type="button" class="btn btn-sign-up" id="sign-up">Sign Up</button>
                </div>
              </div>
            </div>
          </div>
      </span>  
  </div>
</nav>
<script>
  $('a[href*="#"]').on('click', function(e) {
  e.preventDefault()

  $('html, body').animate(
    {
      scrollTop: $($(this).attr('href')).offset().top,
    },
    500,
    'linear'
  )
})
</script>
<%= stylesheet_link_tag 'store-front/nav.css' %>
<%= javascript_include_tag 'store-front/authentication.js' %>