config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   devise_for :users, controllers: {
        sessions: 'users/sessions'
      }


  get 'authentication/sign_up'
  get 'authentication/sign_in'
  root 'pages#home'
  get 'announcement/:id', to: 'pages#announcement', as: :announcement
  get 'product/:id', to: 'pages#product', as: :product
  get 'order_history', to: 'pages#order_history', as: :order_history
  get 'order_product', to: 'pages#order_product'
  get 'contact_us', to: 'pages#contact_us'
  get 'add_to_cart', to: 'pages#add_to_cart'
  get 'get_product', to: 'pages#get_product'
  get 'contact', to: 'pages#contact', as: :contact
  get 'blogs', to: 'pages#blogs', as: :blogs
  get 'blog/:id', to: 'pages#blog', as: :blog
  get 'get_local_storage', to: 'pages#get_local_storage'
  get 'checkout_steps/get_local_storage', to: 'checkout_steps#get_local_storage'
  get 'cart',  to: 'pages#cart'
  get 'reply', to: 'pages#reply'
  get 'increase_product_quantity', to: 'pages#increase_product_quantity'
  get 'decrease_product_quantity', to: 'pages#decrease_product_quantity'
  get 'delete_cart_product', to: 'pages#delete_cart_product'
  get 'get_sub_total', to: 'pages#get_sub_total'
  get '/execute', to: 'checkout_steps#execute'
  get '/redirect_to_paypal', to: 'checkout_steps#redirect_to_paypal', as: :paypal
  get 'continue_to_shipping_method', to: 'checkout_steps#continue_to_shipping_method'
  get 'complete_order', to: 'checkout_steps#complete_order'
  get 'get_nearest_city', to: 'checkout_steps#get_nearest_city'
  get 'admin/login', to: 'admin_authentication#admin_login_page'
  get 'admin_login_action', to: 'admin_authentication#admin_login_action'
  resources :checkout_steps, as: :checkout_steps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/checkout_steps_controller.rb
# frozen_string_literal: true

class CheckoutStepsController < ApplicationController
  include Wicked::Wizard
  steps :customer_information, :shipping_method, :payment_method
  $customer_id
  def get_city(city)
    $city = city
  end
  
  def additional_fee(additional,city_code,total_weight)
    $additional = additional
    pp '-------------==----'
    pp $additional
    pp '----------------'
    $city_code = city_code
    $total_weight = total_weight
  end

  def get_local_storage 
    decoded_hash = JWT.decode(params[:auth_token], Rails.application.secrets.secret_key_base)
    decoded_hash[0].each { |customer_id| $customer_id = customer_id[1] }
  end
 
  def continue_to_shipping_method
    if params[:is_save_info_checked] == 'true'
      customer_shipping_address = CustomerShippingAddress.new
      customer_shipping_address.email_address = params[:email]
      customer_shipping_address.first_name    = params[:fname]
      customer_shipping_address.last_name     = params[:lname]
      customer_shipping_address.customer_id   = $customer_id.to_i
      customer_shipping_address.address       = params[:address]
      customer_shipping_address.apartment     = params[:apartment]
      customer_shipping_address.city          = params[:city]
      customer_shipping_address.country       = params[:country]
      customer_shipping_address.postal_code   = params[:postal]
      customer_shipping_address.is_save_info  = true
      render json: 'shipping address saved successfuly'.to_json if customer_shipping_address.save!
    else
      customer_shipping_address = CustomerShippingAddress.new
      customer_shipping_address.email_address = params[:email]
      customer_shipping_address.first_name    = params[:fname]
      customer_shipping_address.last_name     = params[:lname]
      customer_shipping_address.customer_id   = $customer_id.to_i
      customer_shipping_address.address       = params[:address]
      customer_shipping_address.apartment     = params[:apartment]
      customer_shipping_address.city          = params[:city]
      customer_shipping_address.country       = params[:country]
      customer_shipping_address.postal_code   = params[:postal]
      customer_shipping_address.is_save_info  = false
      render json: 'shipping address saved successfuly'.to_json if customer_shipping_address.save!
    end
  end

  def complete_order
    if params[:standard_shipping] == 'false'
      customer_shipping_address = CustomerShippingAddress.new
      customer_shipping_address.first_name   = params[:fname]
      customer_shipping_address.first_name   = params[:lname]
      customer_shipping_address.customer_id  = $customer_id.to_i
      customer_shipping_address.address      = params[:address]
      customer_shipping_address.apartment    = params[:apartment]
      customer_shipping_address.city         = params[:city]
      customer_shipping_address.country      = params[:country]
      customer_shipping_address.postal_code  = params[:postal]
      customer_shipping_address.is_save_info = true
      customer_shipping_address.save!
    end
    render json: params.to_json
  end

  def redirect_to_paypal
    cart_product = CartProduct.new
    cart = Cart.find_by_customer_id($customer_id.to_i)
    cart_products = CartProduct.where(cart_id: cart.id)
    base_url = request.base_url
    redirect_to cart_product.paypal_url($additional.to_i, cart_products, base_url)
  end

  def execute
    payment = PayPal::SDK::REST::Payment.find(params[:paymentId])
    transactions = payment.links.find { |v| v.rel == 'approval_url' }
    if payment.execute(payer_id: params[:PayerID])
      subtotal = 0
      # get the cart of current user
      cart = Cart.find_by_customer_id($customer_id.to_i)

      # get the sub total of all product for the specific customer in cart
      CartProduct.where(cart_id: cart.id).each do |cart_product|
        subtotal += cart_product.product.price * cart_product.quantity
      end

      # shipping_address = JSON.parse(payment.to_json)["payer"]["payer_info"]["shipping_address"]
      transaction_id = JSON.parse(payment.to_json)['transactions'][0]['related_resources'][0]['sale']['id']
      customer_shipping_address = CustomerShippingAddress.where(customer_id: $customer_id.to_i)
      # create new order
      order = Order.new
      order.total = subtotal
      order.customer_id = $customer_id
      order.payment_order_status_id = 1
      order.customer_shipping_address_id = customer_shipping_address.last.id
      order.paypal_transaction = transaction_id
      if order.save
        cart = Cart.find_by_customer_id($customer_id.to_i)
        CartProduct.where(cart_id: cart.id).each do |cp|
          cp_subtotal = 0
          cp_subtotal += cp.product.price * cp.quantity
          order_product = OrderProduct.new
          order_product.order_id = order.id
          order_product.product_id = cp.product_id
          order_product.sub_total = cp_subtotal
          order_product.save
        end
    end

      # redirect to the cart page if paypal was success
      redirect_to transactions.href.to_s
    else
      payment.error # Error Hash
    end
  end

  def show
    @sub_total = 0
    @cart_quantity = 0
    total = 0
    cart = Cart.find_by_customer_id($customer_id)
    @cart_product = CartProduct.where(cart_id: cart.id)

    @cart_product.where(cart_id: cart.id).each.each do |cart_product|
      @sub_total += cart_product.product.price * cart_product.quantity
      @cart_quantity += cart_product.quantity.to_i
    end

    case step
    when :customer_information
      pp 'customer information'
    when :shipping_method
      @customer_shipping_address = CustomerShippingAddress.where(customer_id: $customer_id).last
      pp 'additional'
      pp '----------------------'
      pp @additional = $additional
      pp '----------------------'
    when :payment_method
      @city = $city unless $city.nil?
      @customer_shipping_address = CustomerShippingAddress.where(customer_id: $customer_id).last
      @additional = $additional
    end
    render_wizard
  end

  def get_nearest_city
    city = City.find_by_sql("SELECT id,name,city_code,lat,lng, ((ACOS(SIN(#{params[:lat]} * PI() / 180)
                             * SIN(lat * PI() / 180) + COS(#{params[:lat]} * PI() / 180) * COS(lat * PI() / 180)
                             * COS((#{params[:lng]} - lng) * PI() / 180)) * 180 / PI()) * 60 * 1.1515)
                             AS distance FROM cities HAVING distance <='20' ORDER BY distance ASC LIMIT 0,10")
    render json: $city
    get_city(city)
    pp calculate($city)
  end

  def calculate(city_result)
    city_code = ''
    additional = 0
    sub_total = 0
    total_weight = 0
    cart = Cart.find_by_customer_id($customer_id)
    CartProduct.where(cart_id: cart.id).each.each do |cart_product|
      total_weight += cart_product.product.weight * cart_product.quantity
      sub_total += cart_product.product.price * cart_product.quantity
    end

    city_result.each { |city| city_code = city.city_code }

    case city_code
    when 'MNL'
      case total_weight
      when 0..5 then additional = 100.00
      when 6..49 then additional = 115.89
      when 50..249 then additional = 130.22
      when 250..999 then additional = 143.01
      when total_weight >= 1000 then additional = 154.2
      end
    when 'BOAC'
      case total_weight
      when 0..5 then additional = 200.00
      when 6..49 then additional = 221.96
      when 50..249 then additional = 242.36
      when 250..999 then additional = 261.22
      when total_weight >= 1000 then additional = 278.48
      end
    when 'CALAPAN'
      case total_weight
      when 0..5 then additional = 200.00
      when 6..49 then additional = 219.99
      when 50..249 then additional = 238.42
      when 250..999 then additional = 255.31
      when total_weight >= 1000 then additional = 270.6
      end
    when 'CRK'
      case total_weight
      when 0..5 then additional = 120.00
      when 6..49 then additional = 136.45
      when 50..249 then additional = 151.339
      when 250..999 then additional = 164.689
      when total_weight >= 1000 then additional = 176.43999999999997
      end
    when 'LUCENA'
      case total_weight
      when 0..5 then additional = 200.00
      when 6..49 then additional = 220.21
      when 50..249 then additional = 238.86
      when 250..999 then additional = 255.97
      when total_weight >= 1000 then additional = 271.48
      end
    when 'URDANETA'
      case total_weight
      when 0..5 then additional = 200.00
      when 6..49 then additional = 225.20
      when 50..249 then additional = 248.83
      when 250..999 then additional = 270.94
      when total_weight >= 1000 then additional = 291.44
      end
    when 'BAGUIO'
      case total_weight
      when 0..5 then additional = 200.00
      when 6..49 then additional = 228.74
      when 50..249 then additional = 255.92
      when 250..999 then additional = 281.56
      when total_weight >= 1000 then additional = 305.6
      end
    when 'BCD'
      case total_weight
      when 0..5 then additional = 150.00
      when 6..49 then additional = 178.44
      when 50..249 then additional = 205.0
      when 250..999 then additional = 229.42
      when total_weight >= 1000 then additional = 251.89
      end
    when 'BXU'
      case total_weight
      when 0..5 then additional = 150.00
      when 6..49 then additional = 180.82
      when 50..249 then additional = 209.76
      when 250..999 then additional = 236.82
      when total_weight >= 1000 then additional = 262.28
      end
    when 'SUG'
      case total_weight
      when 0..5 then additional = 220.00
      when 6..49 then additional = 265.55
      when 50..249 then additional = 310.86
      when 250..999 then additional = 354.68
      when total_weight >= 1000 then additional = 395.74
      end
    when 'CGY'
      case total_weight
      when 0..5 then additional = 150.00
      when 6..49 then additional = 184.74

app/helpers/checkout_steps_helper.rb
# frozen_string_literal: true

module CheckoutStepsHelper
end

app/views/checkout_steps/customer_information.html.erb
<div class="container">
	  <div class="row">
		  	<div class="col-md-8" >
				<div class="row">
					  <div class="col-md-12">
					    <ul class="stepper stepper-horizontal">

					      <!-- First Step -->
					      <li class="active">
					        <a href="#!">
					          <span class="circle">1</span>
					          <span class="label">Customer Info</span>
					        </a>
					      </li>

					      <!-- Second Step -->
					      <li>
					        <a href="#!">
					          <span class="circle">2</span>
					          <span class="label">Shipping Method</span>
					        </a>
					      </li>

					      <!-- Third Step -->
					      <li>
					        <a href="#!">
					          <span class="circle">3</span>
					          <span class="label">Payment Method</span>
					        </a>
					      </li>
					    </ul>
					  </div>


					 <div class="col-md-12 col-lg-12">
	
						  <div class="col-md-12 col-lg-12">
						  	<br>
						  	<h3>Contact Information</h3>
						  </div>
						  
						  <div class="col-md-8 col-lg-8">
						  	 <input type="text" class="form-control validate" placeholder="Email Address" id="email_address">
						  </div>
					  
						  <div class="col-md-12 col-lg-12">
						  	<br>
						  	<h3>Shipping address</h3>
						  </div>
						  
						  <div class="col-md-12 col-lg-12">
							<div class="row">
							    <div class="col-md-4 col-lg-4">
									<div class="md-form">
									  <input type="text" id="fname" class="form-control validate">
									  <label for="fname">Firstname</label>
									</div>
							    </div>
							    <div class="col-md-4 col-lg-4">
							    	<div class="md-form">
									  <input type="text" id="lname" class="form-control validate">
									  <label for="lname">Lastname</label>
									</div>
							    </div>
							    <div class="col-md-8 col-lg-8">
							 	   <div class="md-form">
									  <input type="text" id="address" class="form-control">
									  <label for="address">Address</label>
									</div>
							    </div>
							    <div class="col-md-8 col-lg-8">
							     	<div class="md-form">
									  <input type="text" id="apartment" class="form-control">
									  <label for="apartment">Apartment, suite, etc. (optional)</label>
									</div>
							    </div>
							    <div class="col-md-4 col-lg-4"></div>
							    <div class="col-md-8 col-lg-8">
							     	<div class="md-form">
									  <input type="text" id="city" class="form-control" placeholder="">
									  <label for="city">City</label>
									</div>
							    </div>
							    <div class="col-md-4 col-lg-4"></div>
							    <div class="col-md-4 col-lg-4">
							     <br>	
							      <select id="country" class="form-control">
							      	<option>Phillippines</option>
							      </select>
							    </div>
							    <div class="col-md-4 col-lg-4">
							        <div class="md-form">
									  <input type="text" id="postal" class="form-control">
									  <label for="postal">Postal Code</label>
									</div>
							    </div>
							</div>
						  </div>
					 </div>
				</div>	
			</div>
			<div class="col-md-4 col-lg-4 col-sm-12">
			  <br><br><br><br>
			  <%= render 'shared/total', cart_product: @cart_product, sub_total: @sub_total, cart_quantity: @cart_quantity, additional: nil %>	
			</div>
			

			<div class="col-md-8 col-lg-8">
			    <div class="custom-control custom-checkbox">
				  &nbsp;<input type="checkbox" class="custom-control-input" id="save_this_info" checked>
				  <label class="custom-control-label" for="save_this_info">Save this information for next time</label>
				</div>
			</div>
			<div class="col-md-8 col-lg-8">
				<button class="btn btn-primary" id="continue_to_shipping_method">Continue to Shipping Method</button>
			</div>
	  </div>
	  <br>`
</div>	

<%= javascript_include_tag 'store-front/payment-method.js' %>

app/views/checkout_steps/payment_method.html.erb
<div class="container">
	  <div class="row">
		  	<div class="col-md-8">
			  <!-- Horizontal Steppers -->
						
							  <div class="col-md-12 col-lg-12 ">
							    <!-- Stepers Wrapper -->
							    <ul class="stepper stepper-horizontal">
							      <!-- First Step -->
							      <li>
							        <a href="#!">
							          <span class="circle">1</span>
							          <span class="label">Customer Info</span>
							        </a>
							      </li>

							      <!-- Second Step -->
							      <li>
							        <a href="#!">
							          <span class="circle">2</span>
							          <span class="label">Shipping Method</span>
							        </a>
							      </li>

							      <!-- Third Step -->
							      <li class="active">
							        <a href="#!">
							          <span class="circle">3</span>
							          <span class="label">Payment Method</span>
							        </a>
							      </li>
							    </ul>
							    <!-- /.Stepers Wrapper -->
							  </div>
							  <div class="col-md-12 col-lg-12">
							    <!-- Stepers Wrapper -->
							    <div class="card">
								  <ul class="list-group list-group-flush">
								    <li class="list-group-item">
                                      <div class="col-lg-4 col-md-4">
                                        <label>Contact</label>	
                                      </div>
                                      <div class="col-lg-8 col-md-8">
                                        <% unless @customer_shipping_address.nil? %>
                                            <%= "#{@customer_shipping_address.email_address}" unless @customer_shipping_address.email_address.nil? %> 
                                        <% end %>
                                      </div>
								    </li>
								    <li class="list-group-item">
                                      <div class="col-lg-4 col-md-4">
                                      	<label>Ship to</label>	
                                      </div>
                                      <div class="col-lg-8 col-md-8">
                                        <% unless @customer_shipping_address.nil? %>
                                            <%= "#{@customer_shipping_address.address}," unless @customer_shipping_address.address.nil? %>
                                            <%= "#{@customer_shipping_address.apartment}," unless @customer_shipping_address.apartment.nil? %> 
                                            <%= "#{@customer_shipping_address.address}," unless @customer_shipping_address.address.nil? %>
                                            <%= "#{@customer_shipping_address.country}" unless @customer_shipping_address.country.nil? %>  
                                      	<% end %> 	
                                      </div>
								    </li>
								    <li class="list-group-item">
                                      <div class="col-lg-4 col-md-4">
                                        <label>Method</label>	
                                      </div>
                                      <div class="col-lg-8 col-md-8">
                                        <label>Standard Shipping - NCR</label>
                                      </div>
								    </li>
								  </ul>
								</div>
							    <!-- /.Stepers Wrapper -->
							  </div>
                              <div class="col-md-12">
                              	<br>
                              	<h4>Shipping Adrress</h4>
                              </div>
							  <div class="col-md-12 col-lg-12">
							    <!-- Stepers Wrapper -->
							    <div class="card">
								  <ul class="list-group list-group-flush">
								    <li class="list-group-item">
									   <div class="custom-control custom-radio">
										  <input type="radio" class="custom-control-input" id="defaultChecked" name="defaultExampleRadios" checked>
										  <label class="custom-control-label" for="defaultChecked">Standard Shipping - NCR</label>
										</div>
								    </li>
								    <li class="list-group-item">
									   <div class="custom-control custom-radio">
										  <input type="radio" class="custom-control-input" id="defaultUnchecked" name="defaultExampleRadios">
										  <label class="custom-control-label" for="defaultUnchecked">Use a different billing address</label>
										</div>
								    </li>
								    <li class="list-group-item" id="billing-address">
                                       <div class="row">
                                       	   <div class="col-lg-6 col-md-6">
	                                       	 <div class="md-form">
											  <input type="text" id="fname" class="form-control">
											  <label for="fname">Firstname</label>
											 </div>
	                                       </div>
	                                       <div class="col-lg-6 col-md-6">
	                                       	 <div class="md-form">
											  <input type="text" id="lname" class="form-control">
											  <label for="lname">Lastname</label>
											 </div>
	                                       </div>
	                                       <div class="col-lg-12 col-md-12">
	                                       	 <div class="md-form">
											  <input type="text" id="address" class="form-control">
											  <label for="address">Address</label>
											 </div>
	                                       </div>
	                                       <div class="col-md-12 col-lg-12">
										     	<div class="md-form">
												  <input type="text" id="apartment" class="form-control">
												  <label for="apartment">Apartment, suite, etc. (optional)</label>
												</div>
										   </div>
										   <div class="col-md-12 col-lg-12">
										     	<div class="md-form">
												  <input type="text" id="billing_city" class="form-control" placeholder="">
												  <label for="apartment">City</label>
												</div>
										   </div>
										   <div class="col-md-6 col-lg-6">
										   	 <br>
										      <select id="country" class="form-control">
										      	<option>Phillippines</option>
										      </select>
										   </div>
										   <div class="col-md-6 col-lg-6">
										        <div class="md-form">
												  <input type="text" id="postal" class="form-control">
												  <label for="postal">Postal Code</label>
												</div>
										    </div>
                                       </div>
								    </li>	
								  </ul>
								</div>
							    <!-- /.Stepers Wrapper -->
							  </div>
							  <br>
							  <div class="col-md-8 col-lg-8">
								<%= link_to '<button class="btn btn-primary" id="complete_order">Complete Order</button>'.html_safe, paypal_path %>
							  </div>
							  <br>
			</div>
			<div class="col-md-4">
			  <br><br><br><br>
			  <%= render 'shared/total', cart_product: @cart_product, sub_total: @sub_total, cart_quantity: @cart_quantity, additional:  @additional %>	
			</div>

	  </div>
</div>	
<%= javascript_include_tag 'store-front/payment-method.js' %>

app/views/checkout_steps/shipping_method.html.erb
<div class="container">
	  <div class="row">
		  	<div class="col-md-8">
			  <!-- Horizontal Steppers -->
						
							  <div class="col-md-12 col-lg-12 ">
							    <!-- Stepers Wrapper -->
							    <ul class="stepper stepper-horizontal">
							      <!-- First Step -->
							      <li>
							        <a href="#!">
							          <span class="circle">1</span>
							          <span class="label">Customer Info</span>
							        </a>
							      </li>

							      <!-- Second Step -->
							      <li class="active">
							        <a href="#!">
							          <span class="circle">2</span>
							          <span class="label">Shipping Method</span>
							        </a>
							      </li>

							      <!-- Third Step -->
							      <li>
							        <a href="#!">
							          <span class="circle">3</span>
							          <span class="label">Payment Method</span>
							        </a>
							      </li>
							    </ul>
							    <!-- /.Stepers Wrapper -->
							  </div>
							  <div class="col-md-12 col-lg-12">
							    <!-- Stepers Wrapper -->
							    <div class="card">
								  <ul class="list-group list-group-flush">
								    <li class="list-group-item">
                                      <div class="col-lg-4 col-md-4">
                                        <label>Contact</label>	
                                      </div>
                                      <div class="col-lg-8 col-md-8">
                                        <% unless @customer_shipping_address.nil? %>
                                            <%= "#{@customer_shipping_address.email_address}" unless @customer_shipping_address.email_address.nil? %> 
                                        <% end %>
                                      </div>
								    </li>
								    <li class="list-group-item">
                                      <div class="col-lg-4 col-md-4">
                                      	<label>Ship to</label>	
                                      </div>
                                      <div class="col-lg-8 col-md-8">
                                        <% unless @customer_shipping_address.nil? %>
                                            <%= "#{@customer_shipping_address.address}," unless @customer_shipping_address.address.nil? %>
                                            <%= "#{@customer_shipping_address.apartment}," unless @customer_shipping_address.apartment.nil? %> 
                                            <%= "#{@customer_shipping_address.address}," unless @customer_shipping_address.address.nil? %>
                                            <%= "#{@customer_shipping_address.country}" unless @customer_shipping_address.country.nil? %>  
                                      	<% end %> 	
                                      </div>
								    </li>
								  </ul>
								</div>
							    <!-- /.Stepers Wrapper -->
							  </div>
                              <div class="col-md-12">
                              	<br>
                              	<h4>Shipping Adrress</h4>
                              </div>
							  <div class="col-md-12 col-lg-12">
							    <!-- Stepers Wrapper -->
							    <div class="card">
								  <ul class="list-group list-group-flush">
								    <li class="list-group-item">
									    <div class="custom-control custom-radio">
										  <input type="radio" class="custom-control-input" id="defaultChecked" name="defaultExampleRadios" checked>
										  <label class="custom-control-label" for="defaultChecked">	Standard Shipping - NCR</label>
										</div>
								    </li>
								  </ul>
								</div>
							    <!-- /.Stepers Wrapper -->
							  </div>
							  <br>
							  <div class="col-md-8 col-lg-8">
								<button class="btn btn-primary" id="continue_to_payment_method">Continue to Payment Method</button>
							  </div>
							  <br>
			</div>
			<div class="col-md-4">
			  <br><br><br><br>
			  <%= render 'shared/total', cart_product: @cart_product, sub_total: @sub_total, cart_quantity: @cart_quantity, additional:  @additional %>	
			</div>

	  </div>
</div>	
<%= javascript_include_tag 'store-front/payment-method.js' %>